name: Build

on:
  push:
    branches: [ development, master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Dependencies
        run: |
          brew bundle

      - name: Build (Release)
        run: bundle exec fastlane local_release
